### ISSUE TITLE
Questions about the new software

### ISSUE THREAD

**Issue by meyepasc** [MarkMindCkm/MarkMind-ltd#1]
Thank you very much for the development of this software! I was really looking forward to it. However, I am not an IT expert and still have a few questions about setting up the software:

1. I currently use the obsididian-markmind-plugin to sort my literature and view it with the pdf-annotator. I have created several mind maps for this purpose. If I now want to switch to the newly developed software, can I use the existing mind-maps from obsidian in the new software? If so, how? And will the "jump-to" PDF links still work?

2. You wrote that the new software can also be used with Obsidian. What does that mean and how can I do that?

3. I currently have the subscription version of obsidian-markmind and would now like to buy the forever version of the new software. Will the forever version of the new software also be supported with updates? Because with obsididan-markmind only the subscription version was provided with updates.

**Comment by MarkMindCkm** [comment]
1. Back up your data
2. you can select obsidian vault folder as folder of  markmind vault  or select folder in vault of obsidian as as folder of  markmind vault .
![99af33833bbae51f4a4c8b3390b1d79](https://github.com/MarkMindCkm/MarkMind-ltd/assets/18719494/d1167e74-6ea4-4f35-90ca-ef9d59de8f53)

3. markmind software can open mindmap and  pdf annotate of obsidian markmind
4. software will continue to update
5. It is recommended that you familiarize with the software functions first, and then use it with obsidian

**Comment by meyepasc** [comment]
Thank you for your quick reply! Unfortunately, the PDF-Links doesn't work in the markmind software. If I click on a node, the PDF doesn't jump to it and in the PDF are no highlights. Maybe it's because I used the "anno" style for annotations instead of "markdown"? Will the mark mind software support the "anno" style in future?

**Comment by MarkMindCkm** [comment]
> Thank you for your quick reply! Unfortunately, the PDF-Links doesn't work in the markmind software. If I click on a node, the PDF doesn't jump to it and in the PDF are no highlights. Maybe it's because I used the "anno" style for annotations instead of "markdown"? Will the mark mind software support the "anno" style in future?

- the annos format is not yet supported
- yes ,it will be support

**Comment by MarkMindCkm** [comment]
have support
