### ISSUE TITLE
mac 打开pdf 无法左右分屏

### ISSUE THREAD

**Issue by qin-gao-tfs** [MarkMindCkm/MarkMind-ltd#2]
<img width="1220" alt="image" src="https://github.com/MarkMindCkm/MarkMind-ltd/assets/52768447/15776307-e691-435c-adcf-92241f79d433">
版本0.08

**Comment by MarkMindCkm** [comment]
可以拖动，如下所示

https://github.com/MarkMindCkm/MarkMind-ltd/assets/18719494/275ff2c4-16fa-4a6d-b132-206abf9c2900
